# Generated by Django 3.1.6 on 2021-03-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20210321_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_info',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
