# Generated by Django 3.1.6 on 2021-02-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0002_remove_timeslot_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='friendly_name',
        ),
    ]
