# Generated by Django 3.1.6 on 2021-02-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0003_remove_time_friendly_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
