# Generated by Django 3.1.6 on 2021-02-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0004_timeslot_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='name',
        ),
        migrations.AddField(
            model_name='day',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
