# Generated by Django 3.1.6 on 2021-02-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0006_auto_20210218_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='available_slots',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
