# Generated by Django 3.1.6 on 2021-03-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0007_auto_20210225_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='time',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='EndTime'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='StartTime'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeslot.day'),
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
