# Generated by Django 3.1.6 on 2021-03-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0008_auto_20210316_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='friendly_name',
        ),
    ]
