# Generated by Django 3.1.6 on 2021-03-16 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0009_remove_day_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='available_slots',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(help_text='Please use the following format: <em>XX:XX</em>', null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(help_text='Please use the following format: <em>XX:XX</em>', null=True, verbose_name='Start Time'),
        ),
    ]
