# Generated by Django 3.1.6 on 2021-03-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0011_auto_20210316_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
