# Generated by Django 3.1.6 on 2021-08-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0012_day_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='slot_reserved',
            field=models.BooleanField(null=True),
        ),
    ]
