# Generated by Django 3.1.6 on 2021-03-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20210212_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='allergens',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='allergens',
            field=models.ManyToManyField(to='menu.Allergens'),
        ),
    ]
