# Generated by Django 3.1.6 on 2021-03-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20210320_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='allergens',
            field=models.ManyToManyField(blank=True, to='menu.Allergens'),
        ),
    ]
